# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('env', models.CharField(max_length=255)),
                ('tests', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
